# Generated by Django 5.2.4 on 2025-07-16 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('when', models.CharField(blank=True, max_length=100, null=True, verbose_name='いつの話？')),
                ('situation', models.CharField(blank=True, max_length=200, null=True, verbose_name='どんな状況？')),
                ('characters', models.CharField(blank=True, max_length=200, null=True, verbose_name='登場人物の関係は？')),
                ('punchline', models.TextField(blank=True, null=True, verbose_name='オチは？')),
                ('content', models.TextField(blank=True, verbose_name='生成された原稿')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
