# Generated by Django 5.2.4 on 2025-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='post',
            name='punchline',
        ),
        migrations.RemoveField(
            model_name='post',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='when',
        ),
        migrations.AddField(
            model_name='post',
            name='key_item',
            field=models.CharField(blank=True, max_length=100, verbose_name='物語のキーアイテムは？'),
        ),
        migrations.AddField(
            model_name='post',
            name='protagonist',
            field=models.CharField(blank=True, max_length=100, verbose_name='主人公はどんな人？'),
        ),
        migrations.AddField(
            model_name='post',
            name='setting_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='舞台の具体的な様子は？'),
        ),
        migrations.AddField(
            model_name='post',
            name='twist',
            field=models.TextField(blank=True, verbose_name='意外な展開やどんでん返しは？'),
        ),
    ]
